framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            'assets/': ''
#            '/home/tac/g/tacman/jstree': '@tacman1123/jstree-esm-local'
