survos_base_bundle_oauth:
    resource: '@SurvosBaseBundle/Controller/OAuthController.php'
    prefix: /
    type: annotation


app_change_locale: {path: '/change-locale/{_locale}', controller: 'Survos\BaseBundle\Controller\LandingController::changeLocale'}

survos_landing: {path: /landing, controller: 'Survos\BaseBundle\Controller\LandingController::landing'}
app_heroku: {path: /heroku, controller: 'Survos\BaseBundle\Controller\LandingController::heroku'}
app_logo: {path: /logo, controller: 'Survos\BaseBundle\Controller\LandingController::logo'}
app_profile: {path: /profile, controller: 'Survos\BaseBundle\Controller\LandingController::profile'}
profile: {path: /profile, controller: 'Survos\BaseBundle\Controller\LandingController::profile'}
#logout: {path: /profile, controller: 'Survos\BaseBundle\Controller\LandingController::logout'}
# required if app_profile is used, since you can change the password from the profile
app_change_password: {path: /change-password, controller: 'Survos\BaseBundle\Controller\LandingController::changePassword'}
app_typography: {path: /typography, controller: 'Survos\BaseBundle\Controller\LandingController::typography'}
survos_base_credits: {path: "/credits/{type}", controller: 'Survos\BaseBundle\Controller\LandingController::credits'}
