
# config/routes/survos_landing.yaml
# survos_landing: {path: /, controller: 'Survos\BaseBundle\Controller\LandingController::landing'}
# app_homepage: {path: /, controller: 'Survos\BaseBundle\Controller\LandingController::landing'}
app_logo: {path: /logo, controller: 'Survos\BaseBundle\Controller\LandingController::logo'}
app_profile: {path: /profile, controller: 'Survos\BaseBundle\Controller\LandingController::profile'}
# profile: {path: /profile, controller: 'Survos\BaseBundle\Controller\LandingController::profile'}
# logout: {path: /logout, controller: 'Survos\BaseBundle\Controller\LandingController::logout'}
# required if app_profile is used, since you can change the password from the profile
app_change_password: {path: /change-password, controller: 'Survos\BaseBundle\Controller\LandingController::changePassword'}

survos_landing_bundle_oauth:
    resource: '@SurvosBaseBundle/Controller/OAuthController.php'
    prefix: /
    type: annotation
